---
  title: "February"
  date: "2025-02-14 15:00"
  published-title: "Time and date"
  date-format: "hA dddd, MMM D, YYYY"
---

[Salle 03](../../psc_rooms.qmd), [PariSanté Campus](https://maps.app.goo.gl/cpFoxoZgbT6HCV6x9)

------------------------------------------------------------------------

:::{.callout-tip}
## Seminar time

This seminar is scheduled for **3PM** (not the usual 4PM)
:::

### Necessary conditions for sampling by piecewise deterministic Markov processes

**Manon Michel** *LMBP, Université Clermont-Auvergne*

In Markov Chain Monte Carlo (MCMC) methods, it was long believed to be nearly impossible to break free in a general manner from the stringent sufficient conditions imposed by reversibility. However, Monte Carlo methods based on Piecewise Deterministic Markov Processes (PDMP) have now demonstrated significant acceleration in different systems compared to their reversible counterparts. PDMPs generate sequences of ballistic dynamics governed by Poisson jumps. Yet their efficient extension to arbitrary systems remains challenging. A key effort has been to disentangle the necessary conditions for correctness from the overly restrictive sufficient ones. In this talk, I will explore these distinctions and present irreducible forms of PDMPs for sampling. Furthermore, I will discuss how to introduce more general deterministic flows beyond simple translational ones, defining two fundamental classes: ideal and uniform-ideal flows, which further enhance sampling efficiency.

### Non-reversible lifts of reversible diffusions

**Francis Lörler** *Institute for Applied Mathematics, University of Bonn*

We propose a new concept of lifts of reversible diffusion processes and show that various non-reversible Markov processes arising in applications, including many piecewise-deterministic Markov processes introduced in the sampling literature, are lifts in this sense of simple reversible diffusions. We show that the relaxation time can at most be reduced by a square root through lifting, generalising a related result in discrete time. Finally, we demonstrate how the recently developed approach to quantitative hypocoercivity based on space-time Poincaré inequalities can be rephrased and simplified in the language of lifts and how it can be applied to find optimal lifts.